version: '3.7'
services:
  db:
    image: postgres:12.2-alpine
    env_file:
      - postgres.env

    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    image: node_dev
    depends_on:
      - db
    ports:
      - 3000:3000
